;(async () => {
  const results = []
  const sleep = ms => new Promise(resolve => setTimeout(resolve, ms))
  const q = selector => document.querySelector(selector)
  const check = (condition, label) => { results.push((condition ? 'PASS ' : 'FAIL ') + label) }
  const click = selector => q(selector)?.click()
  localStorage.setItem('yan.onboarded', '1')
  window.__yanStore.getState().openSettings('market')
  for (let i = 0; i < 40 && !q('[data-testid="market-ours"]'); i++) await sleep(100)
  check(!!q('#settings-tab-market'), '独立插件市场入口')
  check(document.querySelectorAll('[data-testid="market-tabs"] [role="tab"]').length === 2, '市场只有两个页签')
  check(!!q('[data-testid="market-hermes-download"]') && q('[data-testid="market-ours"]').textContent.includes('Hermes'), '首批只有实际 Hermes 插件及下载入口')
  check(q('[data-testid="market-ours"]').textContent.includes('装在 Hermes 端'), '清楚标明插件安装端')
  await sleep(2300)
  const ours = q('[data-testid="market-ours-tab"]')
  ours.focus()
  ours.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowRight', bubbles: true }))
  check(document.activeElement === q('[data-testid="market-pi-tab"]'), '方向键移动页签焦点')
  document.activeElement.click()
  await sleep(300)
  check(!!q('[data-testid="market-pi"]'), '方向键切到 pi 插件页')
  for (let i = 0; i < 140 && !q('[data-testid="market-results"] [data-testid="market-choose"]'); i++) await sleep(100)
  check(!!q('[data-testid="market-results"] [data-testid="market-choose"]'), '实际 npm 目录在桌面内返回插件')
  click('[data-testid="market-results"] [data-testid="market-choose"]')
  await sleep(150)
  check(q('[data-testid="pkg-source"]')?.value.startsWith('npm:'), '选择插件填入 pi 原生安装来源')
  check(!!q('[data-testid="pkg-local"]') && !!q('[data-testid="pkg-list"]'), '安装范围与已安装管理保留')
  check(!!q('[data-testid="pkg-install-btn"]') && !q('[data-testid="pkg-result"]'), '选择只准备安装，未偷偷执行安装')
  const panel = q('#settings-tabpanel')
  check(panel.scrollWidth <= panel.clientWidth + 2, '内容没有横向溢出')
  q('[data-testid="market-search"]')?.focus()
  check(document.activeElement === q('[data-testid="market-search"]'), '搜索支持键盘焦点')
  await sleep(2400)
  return results.join('\n')
})()
