/**
 * 图标清单 — 由 reicon@1.2.4 生成，勿手改。
 * 重新生成：node ~/.pi/agent/.dev/build-icons.mjs
 *
 * 用法：
 *   <svg class="ico"><use href="#i-folder"/></svg>          // Outline
 *   <svg class="ico"><use href="#i-folder-f"/></svg>        // Filled
 * 颜色跟随 CSS 的 color，尺寸由 CSS 控制（viewBox 24x24，1.5px 描边）。
 */

export const ICON_VERSION = "1.2.4";

/** 设计稿用的名字 -> sprite 里的 kebab 命名 */
export const ICON_ALIAS = {
  "search": "search",
  "plus": "plus",
  "minus": "minus",
  "x": "x",
  "check": "check",
  "chevron-down": "chevron-down",
  "chevron-right": "chevron-right",
  "chevron-left": "chevron-left",
  "chevron-up": "chevron-up",
  "more-horizontal": "more",
  "menu": "menu",
  "sidebar-left": "sidebar-left",
  "sidebar-right": "sidebar-right",
  "folder": "folder",
  "folder-open": "folder-open",
  "folder-add": "folder-add",
  "file": "file",
  "file-text": "file-text",
  "file-check": "file-check",
  "file-minus": "file-minus",
  "tree": "tree",
  "list-check": "list-check",
  "checklist": "checklist",
  "git-branch": "branch-down",
  "git-commit": "branch-down",
  "git-merge": "branch-up",
  "git-pull-request": "send",
  "branch-down": "branch-down",
  "branch-up": "branch-up",
  "refresh": "refresh",
  "undo": "undo",
  "history": "history",
  "terminal-square": "terminal-square",
  "terminal-circle": "terminal-circle",
  "command": "command",
  "code": "code",
  "code-file": "code-file",
  "play": "play",
  "stop": "stop",
  "pause": "pause",
  "loader": "loader",
  "zap": "flash",
  "flash": "flash",
  "clock": "clock",
  "check-circle": "check-circle",
  "close-circle": "close-circle",
  "alert-triangle": "alert-triangle",
  "alert-circle": "alert-circle",
  "info-circle": "info-circle",
  "information": "information",
  "shield-check": "shield-check",
  "edit": "edit",
  "copy": "copy",
  "clipboard": "clipboard",
  "trash": "trash",
  "eye": "eye",
  "filter": "filter",
  "sort": "sort",
  "layers": "layers",
  "box": "box",
  "package": "package",
  "coin": "coin",
  "coins": "coins",
  "wallet": "wallet",
  "receipt": "receipt",
  "tag": "tag",
  "activity": "activity",
  "trending-up": "activity",
  "cpu-charge": "cpu-charge",
  "cpu": "cpu",
  "settings": "settings",
  "sliders": "sliders",
  "sun": "sun",
  "moon": "moon",
  "globe": "globe",
  "language": "language",
  "translate": "translate",
  "maximize": "maximize",
  "minimize": "minimize",
  "expand": "expand",
  "layout": "layout",
  "drag": "arrange-square",
  "arrange-square": "arrange-square",
  "sparkle": "sparkle",
  "sparkles": "sparkles",
  "brain": "sparkle",
  "message-dots": "message-dots",
  "message-circle": "message-circle",
  "chat-round": "chat-round",
  "send": "send",
  "message": "message",
  "magic": "sparkle"
} as const;

export type IconName = keyof typeof ICON_ALIAS;

/** 全部可用 symbol id（含 Filled 变体） */
export const ICON_IDS = [
  "i-activity",
  "i-activity-f",
  "i-alert-circle",
  "i-alert-circle-f",
  "i-alert-triangle",
  "i-alert-triangle-f",
  "i-arrange-square",
  "i-arrange-square-f",
  "i-box",
  "i-box-f",
  "i-branch-down",
  "i-branch-down-f",
  "i-branch-up",
  "i-branch-up-f",
  "i-chat-round",
  "i-chat-round-f",
  "i-check",
  "i-check-circle",
  "i-check-circle-f",
  "i-check-f",
  "i-checklist",
  "i-checklist-f",
  "i-chevron-down",
  "i-chevron-down-f",
  "i-chevron-left",
  "i-chevron-left-f",
  "i-chevron-right",
  "i-chevron-right-f",
  "i-chevron-up",
  "i-chevron-up-f",
  "i-clipboard",
  "i-clipboard-f",
  "i-clock",
  "i-clock-f",
  "i-close-circle",
  "i-close-circle-f",
  "i-code",
  "i-code-f",
  "i-code-file",
  "i-code-file-f",
  "i-coin",
  "i-coin-f",
  "i-coins",
  "i-coins-f",
  "i-command",
  "i-command-f",
  "i-copy",
  "i-copy-f",
  "i-cpu",
  "i-cpu-charge",
  "i-cpu-charge-f",
  "i-cpu-f",
  "i-edit",
  "i-edit-f",
  "i-expand",
  "i-expand-f",
  "i-eye",
  "i-eye-f",
  "i-file",
  "i-file-check",
  "i-file-check-f",
  "i-file-f",
  "i-file-minus",
  "i-file-minus-f",
  "i-file-text",
  "i-file-text-f",
  "i-filter",
  "i-filter-f",
  "i-flash",
  "i-flash-f",
  "i-folder",
  "i-folder-add",
  "i-folder-add-f",
  "i-folder-f",
  "i-folder-open",
  "i-folder-open-f",
  "i-globe",
  "i-globe-f",
  "i-history",
  "i-history-f",
  "i-info-circle",
  "i-info-circle-f",
  "i-information",
  "i-information-f",
  "i-language",
  "i-language-f",
  "i-layers",
  "i-layers-f",
  "i-layout",
  "i-layout-f",
  "i-list-check",
  "i-list-check-f",
  "i-loader",
  "i-loader-f",
  "i-maximize",
  "i-maximize-f",
  "i-menu",
  "i-menu-f",
  "i-message",
  "i-message-circle",
  "i-message-circle-f",
  "i-message-dots",
  "i-message-dots-f",
  "i-message-f",
  "i-minimize",
  "i-minimize-f",
  "i-minus",
  "i-minus-f",
  "i-moon",
  "i-moon-f",
  "i-more",
  "i-more-f",
  "i-package",
  "i-package-f",
  "i-pause",
  "i-pause-f",
  "i-play",
  "i-play-f",
  "i-plus",
  "i-plus-f",
  "i-receipt",
  "i-receipt-f",
  "i-refresh",
  "i-refresh-f",
  "i-search",
  "i-search-f",
  "i-send",
  "i-send-f",
  "i-settings",
  "i-settings-f",
  "i-shield-check",
  "i-shield-check-f",
  "i-sidebar-left",
  "i-sidebar-left-f",
  "i-sidebar-right",
  "i-sidebar-right-f",
  "i-sliders",
  "i-sliders-f",
  "i-sort",
  "i-sort-f",
  "i-sparkle",
  "i-sparkle-f",
  "i-sparkles",
  "i-sparkles-f",
  "i-stop",
  "i-stop-f",
  "i-sun",
  "i-sun-f",
  "i-tag",
  "i-tag-f",
  "i-terminal-circle",
  "i-terminal-circle-f",
  "i-terminal-square",
  "i-terminal-square-f",
  "i-translate",
  "i-translate-f",
  "i-trash",
  "i-trash-f",
  "i-tree",
  "i-tree-f",
  "i-undo",
  "i-undo-f",
  "i-wallet",
  "i-wallet-f",
  "i-x",
  "i-x-f"
] as const;

export const ICON_GROUPS = {
  "nav 导航": [
    "search",
    "plus",
    "minus",
    "x",
    "check",
    "chevron-down",
    "chevron-right",
    "chevron-left",
    "chevron-up",
    "more-horizontal",
    "menu",
    "sidebar-left",
    "sidebar-right"
  ],
  "folder 文件夹": [
    "folder",
    "folder-open",
    "folder-add",
    "file",
    "file-text",
    "file-check",
    "file-minus",
    "tree",
    "list-check",
    "checklist"
  ],
  "vcs 版本控制": [
    "git-branch",
    "git-commit",
    "git-merge",
    "git-pull-request",
    "branch-down",
    "branch-up",
    "refresh",
    "undo",
    "history"
  ],
  "run 运行": [
    "terminal-square",
    "terminal-circle",
    "command",
    "code",
    "code-file",
    "play",
    "stop",
    "pause",
    "loader",
    "zap",
    "flash",
    "clock"
  ],
  "state 状态": [
    "check-circle",
    "close-circle",
    "alert-triangle",
    "alert-circle",
    "info-circle",
    "information",
    "shield-check"
  ],
  "edit 编辑": [
    "edit",
    "copy",
    "clipboard",
    "trash",
    "eye",
    "filter",
    "sort",
    "layers",
    "box",
    "package"
  ],
  "cost 计费": [
    "coin",
    "coins",
    "wallet",
    "receipt",
    "tag",
    "activity",
    "trending-up",
    "cpu-charge",
    "cpu"
  ],
  "ui 界面": [
    "settings",
    "sliders",
    "sun",
    "moon",
    "globe",
    "language",
    "translate",
    "maximize",
    "minimize",
    "expand",
    "layout",
    "drag",
    "arrange-square"
  ],
  "ai 模型": [
    "sparkle",
    "sparkles",
    "brain",
    "message-dots",
    "message-circle",
    "chat-round",
    "send",
    "message",
    "magic"
  ]
} as const;

/** 取 Outline 图标的 symbol id */
export const iconId = (name: IconName): string => "i-" + ICON_ALIAS[name];

/** 取 Filled 图标的 symbol id */
export const iconIdFilled = (name: IconName): string => "i-" + ICON_ALIAS[name] + "-f";
