/* 示例终端使用真正的 xterm 字符网格；没有连接 PTY 或模型。 */
const q=(s)=>document.querySelector(s), terms={};
function colors(){const css=getComputedStyle(document.documentElement);return {background:css.getPropertyValue('--bg-1').trim(),foreground:css.getPropertyValue('--fg').trim(),cursor:css.getPropertyValue('--fg').trim()};}
function fit(){for(const [id,t] of Object.entries(terms)){const el=q('#'+id+'-terminal');if(el.hidden||!el.clientWidth)continue;t.resize(Math.max(20,Math.floor(el.clientWidth/7.8)),Math.max(5,Math.floor(el.clientHeight/14.95)));}}
function toggle(id){q('.layout').classList.toggle('hide-'+id);requestAnimationFrame(fit);}
function expand(name){const el=q('.'+name),was=el.classList.contains('expanded-pane');document.querySelectorAll('.expanded-pane').forEach(n=>n.classList.remove('expanded-pane'));q('.layout').classList.toggle('expanded',!was);if(!was)el.classList.add('expanded-pane');requestAnimationFrame(fit);}
function theme(){document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';for(const t of Object.values(terms))t.options.theme=colors();}
function menu(){q('.launch-menu').hidden=!q('.launch-menu').hidden;}
function terminalTab(id){document.querySelectorAll('.terminal-host').forEach(n=>n.hidden=n.id!==id+'-terminal');document.querySelectorAll('[data-terminal]').forEach(n=>{n.classList.toggle('on',n.dataset.terminal===id);if(n.dataset.terminal===id)n.hidden=false;});requestAnimationFrame(fit);}
function hideTab(id){q('[data-terminal='+id+']').hidden=true;terminalTab(id==='claude'?'codex':'claude');}
function toolTab(id){q('#changes-content').hidden=id!=='changes';q('#files-content').hidden=id!=='files';q('#changes-tab').classList.toggle('on',id==='changes');q('#files-tab').classList.toggle('on',id==='files');}
for(const grip of document.querySelectorAll('.grip')){grip.addEventListener('pointerdown',e=>{const layout=q('.layout'),kind=grip.dataset.resize,start=e.clientX,width=kind==='term'?q('#term').clientWidth:q('#tools').clientWidth;grip.setPointerCapture(e.pointerId);const move=v=>{layout.style.setProperty('--'+kind+'-width',Math.min(650,Math.max(260,width+start-v.clientX))+'px');fit();};const end=()=>{grip.removeEventListener('pointermove',move);grip.removeEventListener('pointerup',end);};grip.addEventListener('pointermove',move);grip.addEventListener('pointerup',end);});}
async function init(){await document.fonts.load('13px "Maple Mono CN"','Claude 中文');for(const id of ['claude','codex','shell']){const t=new Terminal({fontFamily:'"Maple Mono CN", Consolas, monospace',fontSize:13,lineHeight:1.15,letterSpacing:0,customGlyphs:true,rescaleOverlappingGlyphs:true,cursorBlink:false,theme:colors(),scrollback:100,screenReaderMode:true});t.open(q('#'+id+'-terminal'));try{t.loadAddon(new WebglAddon.WebglAddon());}catch{}terms[id]=t;}
terms.claude.write('\x1b[38;2;217;119;87m  ▄▄▄▄▄\r\n ▐█████▌\x1b[0m   \x1b[1mClaude Code\x1b[0m\r\n\x1b[38;2;217;119;87m  ▀ ▀ ▀\x1b[0m   Native CLI · 预览\r\n            ~\\Desktop\\pi-desktop\r\n\r\n\r\n  终端直接占据面板内容区。\r\n  中文列宽 · ABC 123\r\n\r\n\x1b[90m  此处为 ANSI 示例，无模型请求。\x1b[0m\r\n');
terms.codex.write('\x1b[1m› OpenAI Codex\x1b[0m\r\n\r\n  Native CLI · 预览\r\n  directory: ~\\Desktop\\pi-desktop\r\n\r\n\x1b[90m  每个标签保留自己的终端内容。\x1b[0m\r\n');terms.shell.write('PowerShell · 预览\r\nPS C:\\Users\\YuDaTou\\Desktop\\pi-desktop>\r\n');fit();new ResizeObserver(fit).observe(q('.layout'));window.previewReady=true;}
init();
